### ISSUE TITLE
DR-HTF007S no longer responds on call service set_preset_mode since 0.5.1

### ISSUE THREAD

**Issue by VOSsec** [JeffSteinbok/hass-dreo#47]
Hello @JeffSteinbok ! 👍 

Since version 0.5.1, the fan no longer responds to the call service : set_preset_mode.

https://github.com/JeffSteinbok/hass-dreo/assets/129999011/5c725295-bf30-4f9f-807e-d6c889712dea

For example: when i call {"preset_mode":"sleep"} the fan doesn't change the attribute preset_mode to "sleep". 

Can u pls fix it? ♥️

**Comment by JeffSteinbok** [comment]
I’m sorry, and I’ll fix today after work.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: T. ***@***.***>
Sent: Monday, August 21, 2023 8:39 AM
To: ***@***.***>
Cc: Jeff ***@***.***>; ***@***.***>
Subject: [JeffSteinbok/hass-dreo] DR-HTF007S no longer responds on call service set_preset_mode since 0.5.1 (Issue #47)


Hello @JeffSteinbok<https://github.com/JeffSteinbok> ! 👍

Since version 0.5.1, the fan no longer responds to the call service : set_preset_mode.

https://github.com/JeffSteinbok/hass-dreo/assets/129999011/5c725295-bf30-4f9f-807e-d6c889712dea

For example: when i call {"preset_mode":"sleep"} the fan doesn't change the attribute preset_mode to "sleep".

Can u pls fix it? ♥️

**Comment by JeffSteinbok** [comment]
Fixed in 0.5.2
